name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up PHP with Composer
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Updated to PHP 8.2
          extensions: mbstring, bcmath, pdo, openssl
          ini-values: post_max_size=256M, max_execution_time=300
          coverage: none

      # Step 3: Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-ansi --no-progress --no-scripts --no-interaction

      # Step 4: Set up environment file
      - name: Copy .env.example to .env
        run: cp .env.example .env

      # Step 5: Generate application key
      - name: Generate application key
        run: php artisan key:generate

      # Directory Permission
      - name: Directory Permission
        run: chmod -R 777 storage bootstrap/cache

      - name: phpstan
        run: ./vendor/bin/phpstan analyse app tests --memory-limit=1G

      - name: phpinsights
        run: |
          php artisan insights --no-interaction \
          --min-quality=90 --min-complexity=90 \
          --min-architecture=90 --min-style=90 \
          --ansi --format=github-action

      # Step 6: Run tests (optional)
      - name: Run tests
        run: php artisan test
