name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up PHP with Composer
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, pdo, openssl
          ini-values: post_max_size=256M, max_execution_time=300
          coverage: none

      # Step 3: Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-ansi --no-progress --no-scripts --no-interaction

      # Step 4: Set up environment file
      - name: Copy .env.example to .env
        run: cp .env.example .env

      # Step 5: Generate application key
      - name: Generate application key
        run: php artisan key:generate

      # Step 6: Directory Permission
      - name: Directory Permission
        run: chmod -R 777 storage bootstrap/cache

      # Step 7: Static analysis with PHPStan
      - name: PHPStan Analysis
        run: ./vendor/bin/phpstan analyse app tests --memory-limit=1G

      # Step 8: Code insights with PHPInsights
      - name: PHP Insights
        run: |
          php artisan insights --no-interaction \
          --min-quality=90 --min-complexity=90 \
          --min-architecture=90 --min-style=90 \
          --ansi --format=github-action

      # Step 9: Run tests
      - name: Run tests
        run: php artisan test

      # Step 10: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # step 11 Deployment application to server
      #sshpass -p root@123Root ssh -o StrictHostKeyChecking=no root@157.245.157.100 << 'EOF'
      #ssh -o StrictHostKeyChecking=no root@157.245.157.100 << 'EOF'
      - name: Deploy to Server
        if: success()
        run: |
          sshpass -p root@123Root ssh -o StrictHostKeyChecking=no root@157.245.157.100 << 'EOF'
          cd /var/www/html/laravel-cicd/
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:caches
          // sudo systemctl restart php-fpm
          sudo systemctl restart nginx
          EOF
